#ifndef GPU_IN_OUT_STRUCTS_SCALAR_GLSL
#define GPU_IN_OUT_STRUCTS_SCALAR_GLSL

struct Input {
	STRUCT_LAYOUT(PREC_SCAL_TYPE,x,N);
	STRUCT_LAYOUT(PREC_SCAL_TYPE,v,N);
};

struct Output {
	STRUCT_LAYOUT(PREC_SCAL_TYPE,f,N);
	STRUCT_LAYOUT(PREC_SCAL_TYPE,g,N);
};

#endif /* end of include guard: GPU_IN_OUT_STRUCTS_SCALAR_GLSL */
