#ifndef GPU_IN_OUT_STRUCTS_GLSL
#define GPU_IN_OUT_STRUCTS_GLSL

struct Input {
	//STRUCT_LAYOUT(PREC_VEC_TYPE,x,N);
	STRUCT_LAYOUT(PREC_VEC_TYPE,v,N);
};

struct Output {
	//STRUCT_LAYOUT(PREC_SCAL_TYPE,f,N);
	STRUCT_LAYOUT(PREC_SCAL_TYPE,g,N);
};

#endif /* eNd of iNclude guard: GPU_IN_OUT_STRUCTS_GLSL */
