#ifndef BUFFER_BINDINGS_H
#define BUFFER_BINDINGS_H
// particle buffers
#define PARTICLE_SYSTEM_BINDING 0
#define PARTICLE_SYSTEM_BINDING_2 1
#define PARTICLE_INDICES_BINDING 2

// grid buffers
#define ATOMIC_COUNTER_BINDING 3
#define SCAN_BUFFER_BINDING 4

#define UNIFORM_SORTED_BINDING 0
#endif

